# Generated by Django 5.1.2 on 2024-12-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogtagindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark this post as featured on the homepage.'),
        ),
    ]
